name: Laravel

run-name: ${{ github.actor }} testing laravel app

on:
  push:
    branches: ['main']
  pull_request:
    types: ['closed']
    branches: ['main']

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.x'
        cache: 'npm'
    - name: Setup Node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Copy .envd
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install node dependencies
      run: npm ci
    - name: Setup project
      run: |
        php artisan key:generate
        php artisan optimize:clear
    - name: Directory Permissions
      run: chmod -R 755 storage
    - name: Run test
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    needs: ['laravel-tests']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.x'
        extensions: imagick
    - name: Setup Node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Install node dependencies
      run: npm ci
    - name: Setup project
      run: |
        php artisan key:generate
        php artisan optimize:clear
    - name: Directory Permissons
      run: chmod -R 755 storage
    - name: Run test
      run: php artisan test
